name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build release binary
        run: cargo build --release

      - name: Create tarball
        run: tar -czvf assetm.tar.gz -C target/release assetm

      - name: Calculate SHA-256 checksum
        id: checksum
        run: echo "::set-output name=sha256::$(sha256sum assetm.tar.gz | cut -d' ' -f1)"
